### ISSUE TITLE
video finish

### ISSUE THREAD

**Issue by sanabouchama** [huskeee/tkvideo#13]
How do I detect when video is done playing

**Comment by CoCaptainBlue** [comment]
Hi! I have had same issue. I managed to fix it though. Here is what I did:
![image](https://user-images.githubusercontent.com/108145617/194966846-7c7ae9b3-7fc4-4352-8039-ed57f78d4128.png)

In this part of the library's code, I created an event and I named mine "Completed" (remember you need the << before and after it for the event to generate and work properly) (see the picture)

label.event_generate("<\<Completed>>")

So now in my program I can do something like this to close the video player when the video finishes.

```from tkinter import *
from tkvideo import tkvideo

root = Tk()
root.geometry("660x370")
my_label = Label(root)
my_label.pack()
player = tkvideo(r"OBS Splash Screen.mp4", my_label, loop = 0, size = (1280,720))
player.play()


def endit(event):
    root.destroy()
    
root.bind("<<Completed>>", endit)

root.mainloop()
```
