### ISSUE TITLE
AttributeError: type object 'tkvideo' has no attribute 'tkvideo'

### ISSUE THREAD

**Issue by fredycoding** [huskeee/tkvideo#6]
Hi, i got this error: 
Traceback (most recent call last):
  File "c:\Users\ASUSTANUS\Documents\PYTHON-EXERCISES\prueba.py", line 7, in <module>
    player = tkvideo.tkvideo("video.mp4", my_label, loop = 1, size = (1280,720))
AttributeError: type object 'tkvideo' has no attribute 'tkvideo'

My code is:
`from tkinter import *
from tkvideo import tkvideo

root = Tk()
my_label = Label(root)
my_label.pack()
player = tkvideo.tkvideo("video.mp4", my_label, loop = 1, size = (1280,720))
player.play()

root.mainloop()`

**Comment by wisetux** [comment]
Change line 7
 player = tkvideo("video.mp4", my_label, loop = 1, size = (1280,720))

**Comment by fredycoding** [comment]
Hi wisetus, thanks it works, thank you
