### ISSUE TITLE
video with no sound

### ISSUE THREAD

**Issue by CapitaineCoco** [huskeee/tkvideo#9]
When i play a mp4 video there is no sound. This i my code. I don't know whats wrong.

from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
from ctypes import cast, POINTER
from comtypes import CLSCTX_ALL
from tkinter import *
from tkvideo import tkvideo

#play the rickroll video
root = Tk()
my_label = Label(root)
my_label.pack()
player = tkvideo("E:\RickRoll\RickRoll.mp4", my_label, loop = 100, size = (1920,1080))
player.play()

#put sound to max volume
devices = AudioUtilities.GetSpeakers()
interface = devices.Activate(IAudioEndpointVolume._iid_, CLSCTX_ALL, None)
volume = cast(interface, POINTER(IAudioEndpointVolume))
volume.SetMasterVolumeLevel(0.0, None)

root.attributes('-fullscreen', True)
root.mainloop()

Thanks

**Comment by ghost** [comment]
Tkinter **does not** support the use of audio in videos or audiofiles.
What you could do, is have the video split up into the video file and the audio file. You would need to call the files at the same time seperately, but that would solve your issue.

You could try this:

`from winsound import *`

and then just define a function you can call (by pressing a button for example)

`def play():
    return PlaySound("click_one.wav", SND_FILENAME)`

**OR**

I've also found out that you could use pygame for this:

```
import pygame
from tkinter import *
root = Tk()
pygame.init()
def play():
    pygame.mixer.music.load("Musics/example.mp3") #Loading File Into Mixer
    pygame.mixer.music.play() #Playing It In The Whole Device
Button(root,text="Play",command=play).pack()
root.mainloop()
```

If you want to further look into this, here is a link to the stackoverfow:

https://stackoverflow.com/questions/38966257/how-to-play-sounds-on-python-with-tkinter#:~:text=There%20are%20two%20types%20of%20sound%20you%20can,You%20can%20even%20use%20pyglet%20or%20other%20modules.
